### ISSUE TITLE
NodeSchool International Day

### ISSUE THREAD

**Issue by a0viedo** [nodeschool/buenosaires#25]
Se decidió que sea el Sábado 23 de Mayo. Hasta hay una [página](http://nodeschool.io/international-day/) con información. Necesitamos:
## TODOs
- [X] Un lugar -> Oficinas de Microsoft
- [X] Stickers -> Están en camino
- [X] Sponsors:
  - [Aerolab](https://aerolab.co/) 
  - [Microsoft](http://microsoft.com/)
  - [Coderhouse](http://coderhouse.com/)
  - [StrongLoop](http://strongloop.com/)
- [X] Link de registración
- [x] Hacer el PR al sitio oficial
## Mentores
1. @ivancevich 
2. @jaclar 
3. @diegosanchez 
4. @a0viedo
5. @durancristhian
6. @eafelix 
7. @mgtitimoli
8. @nisnardi
9. @ellames

Nos faltan mentores! Necesitamos por lo menos 1 o 2 más para estar tranquilos.

**Comment by diegosanchez** [comment]
Si NodeSchoolBA va a oficiar de host deberíamos registrarnos en?https://github.com/nodeschool/international-day/issues/8

**Comment by a0viedo** [comment]
@diegosanchez si tal cual, una vez tengamos buena parte de los items completados nos anunciaríamos

**Comment by a0viedo** [comment]
@nodeschool/buenosaires empezamos a cerrar las últimas cosas para el evento! Hasta inclusive tenemos nuevo logo :)

El horario del evento ese día va a ser de 10 a 17hs, lo vamos a realizar en las oficinas de Microsoft y hasta vamos a contar con la posibilidad de hacer live streaming.

@mgtitimoli estaba con el tema de mandar a hacer remeras para los mentores.

Necesitaría que me vayan confirmando quienes van a poder asistir al evento.

**Comment by ivancevich** [comment]
Yo asisto @a0viedo :)

**Comment by jaclar** [comment]
yo voy a estar.
Fundación Telefónica nos preguntó por flyers para ayudar con la difusión.

**Comment by diegosanchez** [comment]
Yo voy a ir.

**Comment by a0viedo** [comment]
@jaclar totalmente! justo estaba pensando en eso, los podemos agregar cómo sponsors y que ayuden en la difusión del evento?

sé que @mgtitimoli tiene flyers

**Comment by hernanhht** [comment]
Me gustaría estar pero sigo de luna de miel hasta el 24.

Abrazo

On Sunday, May 3, 2015, Alejandro Oviedo notifications@github.com wrote:

> @jaclar https://github.com/jaclar totalmente! justo estaba pensando en
> eso, los podemos agregar cómo sponsors y que ayuden en la difusión del
> evento?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/buenosaires/issues/25#issuecomment-98436289
> .

## 

---

Hernán Tierno
htierno@gmail.com

**Comment by eafelix** [comment]
quieren que armemeos una lista de difusion y los canales a cubrir ?

**Comment by a0viedo** [comment]
gracias a todos por participar y por ponerle garra!

@hernanhht solo voy a decir que te perdiste 400 empanadas

**Comment by hernanhht** [comment]
Que bueno que haya salido tan bien. Espero poder estar para la próxima. Me
conformo con los sanguchitos de miga.

On Tuesday, June 2, 2015, Alejandro Oviedo notifications@github.com wrote:

> gracias a todos por participar y por ponerle garra!
> 
> @hernanhht https://github.com/hernanhht solo voy a decir que te
> perdiste 400 empanadas
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/buenosaires/issues/25#issuecomment-107805979
> .

## 

---

Hernán Tierno
htierno@gmail.com
