### ISSUE TITLE
Checklist para la organización del evento

### ISSUE THREAD

**Issue by eafelix** [nodeschool/buenosaires#26]
Aqui va definida la lista para no perder ningún punto en la organización de los eventos. 
Puntos que surgen de nuestra propia experiencia, recomendaciones de otras comunidades, etc.
Obviamente todos somos libres de ir discutiendo y corrigiendo cosas.
- [x]  Confirmar hosts.
- [x]  Confirmar sponsors. 
- [ ]  Confirmar Charla introductoria de Node.js
- [ ]  Confirmar Fecha y Hora antes de promocionar el evento.
- [ ]  Actualizar Web con los datos de sponsors , fechas. 
- [ ]  Actualizar Meetup y abrir la inscripción. 
- [ ]  Generar Formulario de confirmación (Revisar este punto en issue )
- [ ]  Ver extras como stickers , snacks , etc.  
- [ ]  Generar encuesta post evento.

Checklist de items necesarios para el hosting : 
El host del evento debe tener estas características para que la experiencia sea optima y agradable.
- [ ] Equipo de presentación 
- [ ] Disponibilidad de espacio de trabajo compartido para promover la camaradería 
- [ ] Conexiones a red disponibles para todos los invitados
- [ ] Acceso a toma corrientes para las notebooks de los participantes

Checklist de items necesarios para la difusión: 
- [ ] Armado de Material para Redes sociales y Email para difusión.
- [ ] Notificaciones en Twitter periódicas a partir del lanzamiento.
- [ ] Notificaciones en Facebook periódicas a partir del lanzamiento.
- [ ] Notificaciones en Listas de Mail a partir del lanzamiento.

**Comment by jaclar** [comment]
Creo que podemos sacar:
- [ ] Confirmar Charlas ( 2 charlas de 20 a 30 minutos cada uno con espacio a lighting talk).

a lo sumo lo reemplazaría con algo tipo:
- [ ] Confirmar Charla introductorio de node.js

**Comment by a0viedo** [comment]
> Confirmar Fecha y Hora (Preferentemente).

Yo diría obligatoriamente. No podemos publicitar un evento el cual todavía no se sabe el horario...

**Comment by eafelix** [comment]
Si me quedo inconcluso, la idea era dejar en claro de tener la fecha y el horario antes que nada. Corregido

**Comment by a0viedo** [comment]
> Generar encuesta post evento.

casi seguro que tenemos un template de esto en algún lado
